CREATE TABLE TB_CONSULTATION(
	CNSLT_SEQ		INT 			AUTO_INCREMENT PRIMARY KEY
	,NM				VARCHAR(30)		NOT NULL	COMMENT '이름'
	,TEL1			VARCHAR(20)		NOT NULL	COMMENT '기본 연락처'
	,TEL2			VARCHAR(20)		NULL		COMMENT '추가 연락처'
	,ZIP			VARCHAR(5)		NULL		COMMENT '우편번호'
	,ADRES1			VARCHAR(99)		NULL		COMMENT '주소'
	,ADRES2			VARCHAR(99)		NULL		COMMENT '상세주소'
	,SERVICE_CD 	VARCHAR(3) 		NULL 	    COMMENT '서비스코드(TB_CATEGORY 시퀀스 상담)'
	,PRODUCT_NO 	INT 			NULL        COMMENT '상품번호(TB_PRODUCT 시퀀스 예약)'
	,HOPE_DAY		VARCHAR(8)		NULL		COMMENT '희망일'
	,INQRY_CN		LONGTEXT		NOT NULL	COMMENT '문의 내용'
	,REG_DT			DATETIME		DEFAULT CURRENT_TIMESTAMP NOT NULL	COMMENT '문의일시'
	,PW				VARCHAR(99)		NULL		COMMENT '비밀번호'
	,ANSWER			LONGTEXT		NULL		COMMENT '문의 답글'
	,ANSWER_DT		DATETIME		NULL		COMMENT '답글 일시'
	,ANSWER_ID		VARCHAR(30)		NULL		COMMENT '답글 작성자'
	,STTUS_CD		VARCHAR(3)		NULL		COMMENT '진행상태'
	,REQ_TYPE		VARCHAR(3)		NOT NULL	COMMENT '예약,상담 구분코드(001:상담,002:예약)'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='상담 문의 관리 테이블';

CREATE TABLE TB_CASE (
	CASE_SEQ 		INT 			AUTO_INCREMENT PRIMARY KEY
	,SERVICE_CD 	VARCHAR(3) 		NULL 	    COMMENT '서비스코드(TB_CATEGORY 시퀀스 상담)'
	,CASE_SJ		VARCHAR(100)	NOT NULL	COMMENT '제목'
	,CASE_CN 		LONGTEXT 		NULL		COMMENT '내용'
	,REG_NM 		VARCHAR(50) 	NOT NULL	COMMENT '작성자 ID'
	,FILE_SEQ		INT				NOT NULL	COMMENT '대표이미지(TB_FILE)'
	,HASHTAG		VARCHAR(500)	NULL		COMMENT '해시태크'
	,RGS_DT 		DATETIME 		DEFAULT CURRENT_TIMESTAMP NOT NULL	COMMENT '등록일'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='사례 관리 테이블';

CREATE TABLE TB_BOARD (
	BOARD_SEQ 		INT 			AUTO_INCREMENT PRIMARY KEY
	,BOARD_GB 		VARCHAR(10)		NOT NULL 	COMMENT '게시판구분(공지,FAQ,포토...)'
	,NOTICE_YN 		CHAR(1) 		NOT NULL	COMMENT '공지여부'
	,BOARD_SJ		VARCHAR(100)	NOT NULL	COMMENT '제목'
	,BOARD_CN 		LONGTEXT 		NULL		COMMENT '내용'
	,REG_NM 		VARCHAR(100) 	NOT NULL	COMMENT '작성자'
	,RGS_DT 		DATETIME 		DEFAULT CURRENT_TIMESTAMP NOT NULL	COMMENT '등록일'
	,SECRET_YN		CHAR(1) 		NULL		COMMENT '비밀글 여부'
	,SECRET_PW		VARCHAR(1000)	NULL		COMMENT '비밀번호'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='게시판 관리 테이블';

CREATE TABLE TB_FILE_RELATION(
	FILE_RELATE_SEQ	INT				AUTO_INCREMENT PRIMARY KEY
	,FILE_TRGET_SE	VARCHAR(20)		NOT NULL	COMMENT '대상 구분(CNSLT:상담,BOARD:게시판)'
	,FILE_TRGET_SEQ	INT				NOT NULL	COMMENT '대상 고유 번호'
	,FILE_SEQ		INT				NOT NULL	COMMENT '파일 고유 번호'
	,RGS_DT 		DATETIME 		DEFAULT CURRENT_TIMESTAMP NOT NULL	COMMENT '등록일'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='파일 관계 관리 테이블';

CREATE TABLE TB_FILE (
	FILE_SEQ		INT				AUTO_INCREMENT PRIMARY KEY
	,FILE_REAL_NM 	VARCHAR(500)	NOT NULL	COMMENT '진짜 파일 이름'
	,FILE_FAKE_NM 	VARCHAR(500)	NOT NULL	COMMENT '가짜 파일 이름'
	,FILE_PATH	 	VARCHAR(100)	NOT NULL	COMMENT '파일 경로'
	,FILE_EXTSN		VARCHAR(10)		NOT NULL	COMMENT '파일 확장자'
	,FILE_SIZE		INT 			NOT NULL	COMMENT '파일 용량'
	,RGS_DT 		DATETIME 		DEFAULT CURRENT_TIMESTAMP NOT NULL	COMMENT '등록일'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='파일 관리 테이블';

CREATE TABLE TB_MANAGER (
	MNGR_SEQ		INT 			AUTO_INCREMENT PRIMARY KEY
	,MNGR_ID		VARCHAR(50)		NOT NULL UNIQUE	COMMENT '아이디'
	,MNGR_PW		VARCHAR(99)		NOT NULL		COMMENT '비밀번호'
	,MNGR_NM		VARCHAR(20)		NOT NULL		COMMENT '관리자명'
	,MNGR_NCNM		VARCHAR(20)		NOT NULL		COMMENT '등록명칭'
	,MNGR_TEL		VARCHAR(20)		NULL			COMMENT '전화번호'
	,MNGR_STTUS		CHAR(1) 		NOT NULL		COMMENT '상태'
	,RGS_DT 		DATETIME 		DEFAULT CURRENT_TIMESTAMP NOT NULL		COMMENT '등록일'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='관리자 정보 테이블';

CREATE TABLE TB_CMMN_CODE (
	GROUP_CD 		CHAR(3) 		NOT NULL	COMMENT '그룹코드'
	,GROUP_NM 		VARCHAR(99)		NOT NULL	COMMENT '그룹이름'
	,CODE 			CHAR(3)			NOT NULL	COMMENT '코드'
	,CODE_NM 		VARCHAR(99)		NOT NULL	COMMENT '코드이름'
	,CODE_USE_YN 	VARCHAR(1)		NOT NULL	COMMENT '코드사용유무'
	,PRIMARY KEY (GROUP_CD,CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='공통코드 관리 테이블';

CREATE TABLE TB_REVIEW (
	REVIEW_SEQ 		INT 			AUTO_INCREMENT PRIMARY KEY
	,REVIEW_NM		VARCHAR(50)		NOT NULL	COMMENT '작성자 이름'
	,REVIEW_CN 		LONGTEXT 		NOT NULL	COMMENT '후기 내용'
	,STAR_RATE		INT 			NOT NULL	COMMENT '별점 (1-5)'
	,SERVICE_CD		VARCHAR(3)		NULL		COMMENT '서비스 내용 코드'
	,PRODUCT_NO		INT				NULL		COMMENT '상품번호'
	,SVC_DATE		VARCHAR(8)		NULL		COMMENT '서비스 받은 날짜'
	,DISP_YN		CHAR(1) 		NOT NULL	COMMENT '노출여부'
	,PW				VARCHAR(99)		NULL		COMMENT '비밀번호 (수정/삭제용)'
	,RGS_DT 		DATETIME 		DEFAULT CURRENT_TIMESTAMP NOT NULL	COMMENT '등록일'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='리뷰 관리 테이블';





-- 서비스 카테고리 테이블
CREATE TABLE IF NOT EXISTS TB_CATEGORY (
    SERVICE_CD VARCHAR(3) NOT NULL PRIMARY KEY,     -- 서비스 코드 (001, 002, ...)
    SERVICE_NM VARCHAR(100) NOT NULL,               -- 서비스명
    SERVICE_ORDER INT DEFAULT 0,                    -- 정렬 순서
    USE_YN VARCHAR(1) DEFAULT 'Y',                  -- 사용여부 (Y/N)
    DEL_YN VARCHAR(1) DEFAULT 'N',                  -- 삭제여부 (Y/N)
    REG_USER_ID VARCHAR(50),                        -- 등록자 ID
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,      -- 등록일시
    MOD_USER_ID VARCHAR(50),                        -- 수정자 ID
    MOD_DT DATETIME DEFAULT CURRENT_TIMESTAMP       -- 수정일시
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS IDX_CATEGORY_USE ON TB_CATEGORY(USE_YN, DEL_YN);
CREATE INDEX IF NOT EXISTS IDX_CATEGORY_ORDER ON TB_CATEGORY(SERVICE_ORDER, SERVICE_CD);

-- TB_CATEGORY 테이블 코멘트
ALTER TABLE TB_CATEGORY COMMENT = '서비스 카테고리 정보';
ALTER TABLE TB_CATEGORY MODIFY COLUMN SERVICE_CD VARCHAR(3) NOT NULL COMMENT '서비스 코드 (001, 002, ...)';
ALTER TABLE TB_CATEGORY MODIFY COLUMN SERVICE_NM VARCHAR(100) NOT NULL COMMENT '서비스명';
ALTER TABLE TB_CATEGORY MODIFY COLUMN SERVICE_ORDER INT DEFAULT 0 COMMENT '정렬 순서';
ALTER TABLE TB_CATEGORY MODIFY COLUMN USE_YN VARCHAR(1) DEFAULT 'Y' COMMENT '사용여부 (Y/N)';
ALTER TABLE TB_CATEGORY MODIFY COLUMN DEL_YN VARCHAR(1) DEFAULT 'N' COMMENT '삭제여부 (Y/N)';
ALTER TABLE TB_CATEGORY MODIFY COLUMN REG_USER_ID VARCHAR(50) COMMENT '등록자 ID';
ALTER TABLE TB_CATEGORY MODIFY COLUMN REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시';
ALTER TABLE TB_CATEGORY MODIFY COLUMN MOD_USER_ID VARCHAR(50) COMMENT '수정자 ID';
ALTER TABLE TB_CATEGORY MODIFY COLUMN MOD_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시';




-- 상품 테이블 생성
CREATE TABLE IF NOT EXISTS TB_PRODUCT (
    PRODUCT_NO INT AUTO_INCREMENT PRIMARY KEY,       -- 상품번호
    SERVICE_CD VARCHAR(3) NOT NULL,                  -- 서비스코드 (TB_CATEGORY 참조)
    PRODUCT_NM VARCHAR(200) NOT NULL,                -- 상품명
    PRODUCT_DESC LONGTEXT,                           -- 상품 상세설명
    AREA_TYPE VARCHAR(50),                           -- 평형대 (예: 20-30평형)
    ORIGINAL_PRICE INT DEFAULT 0,                    -- 정가
    SALE_PRICE INT DEFAULT 0,                        -- 판매가
    DISCOUNT_RATE INT DEFAULT 0,                     -- 할인율(%)
    SERVICE_TIME VARCHAR(50),                        -- 소요시간 (예: 3-4시간)
    SERVICE_INCLUDES LONGTEXT,                       -- 서비스 포함사항 (JSON 형태)
    DISPLAY_ORDER INT DEFAULT 999,                   -- 노출순서
    DISPLAY_YN VARCHAR(1) DEFAULT 'Y',               -- 노출여부
    SALE_YN VARCHAR(1) DEFAULT 'Y',                  -- 판매여부
    DEL_YN VARCHAR(1) DEFAULT 'N',                   -- 삭제여부
    REG_USER_ID VARCHAR(50),                         -- 등록자
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,       -- 등록일시
    MOD_USER_ID VARCHAR(50),                         -- 수정자
    MOD_DT DATETIME DEFAULT CURRENT_TIMESTAMP,       -- 수정일시
    FOREIGN KEY (SERVICE_CD) REFERENCES TB_CATEGORY(SERVICE_CD)
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS IDX_PRODUCT_SERVICE ON TB_PRODUCT(SERVICE_CD);
CREATE INDEX IF NOT EXISTS IDX_PRODUCT_DISPLAY ON TB_PRODUCT(DISPLAY_YN, DEL_YN);
CREATE INDEX IF NOT EXISTS IDX_PRODUCT_ORDER ON TB_PRODUCT(DISPLAY_ORDER, PRODUCT_NO);
CREATE INDEX IF NOT EXISTS IDX_PRODUCT_SALE ON TB_PRODUCT(SALE_YN, DEL_YN);

-- TB_PRODUCT 테이블 코멘트
ALTER TABLE TB_PRODUCT COMMENT = '상품 정보';
ALTER TABLE TB_PRODUCT MODIFY COLUMN PRODUCT_NO INT AUTO_INCREMENT PRIMARY KEY COMMENT '상품번호';
ALTER TABLE TB_PRODUCT MODIFY COLUMN SERVICE_CD VARCHAR(3) NOT NULL COMMENT '서비스코드';
ALTER TABLE TB_PRODUCT MODIFY COLUMN PRODUCT_NM VARCHAR(200) NOT NULL COMMENT '상품명';
ALTER TABLE TB_PRODUCT MODIFY COLUMN PRODUCT_DESC LONGTEXT COMMENT '상품 상세설명';
ALTER TABLE TB_PRODUCT MODIFY COLUMN AREA_TYPE VARCHAR(50) COMMENT '평형대';
ALTER TABLE TB_PRODUCT MODIFY COLUMN ORIGINAL_PRICE INT DEFAULT 0 COMMENT '정가';
ALTER TABLE TB_PRODUCT MODIFY COLUMN SALE_PRICE INT DEFAULT 0 COMMENT '판매가';
ALTER TABLE TB_PRODUCT MODIFY COLUMN DISCOUNT_RATE INT DEFAULT 0 COMMENT '할인율(%)';
ALTER TABLE TB_PRODUCT MODIFY COLUMN SERVICE_TIME VARCHAR(50) COMMENT '소요시간';
ALTER TABLE TB_PRODUCT MODIFY COLUMN SERVICE_INCLUDES LONGTEXT COMMENT '서비스 포함사항';
ALTER TABLE TB_PRODUCT MODIFY COLUMN DISPLAY_ORDER INT DEFAULT 999 COMMENT '노출순서';
ALTER TABLE TB_PRODUCT MODIFY COLUMN DISPLAY_YN VARCHAR(1) DEFAULT 'Y' COMMENT '노출여부';
ALTER TABLE TB_PRODUCT MODIFY COLUMN SALE_YN VARCHAR(1) DEFAULT 'Y' COMMENT '판매여부';
ALTER TABLE TB_PRODUCT MODIFY COLUMN DEL_YN VARCHAR(1) DEFAULT 'N' COMMENT '삭제여부';
ALTER TABLE TB_PRODUCT MODIFY COLUMN REG_USER_ID VARCHAR(50) COMMENT '등록자';
ALTER TABLE TB_PRODUCT MODIFY COLUMN REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시';
ALTER TABLE TB_PRODUCT MODIFY COLUMN MOD_USER_ID VARCHAR(50) COMMENT '수정자';
ALTER TABLE TB_PRODUCT MODIFY COLUMN MOD_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시';