-- =============================================================================
-- 테이블 및 컬럼 코멘트 추가 스크립트
-- =============================================================================
-- 데이터베이스: careville
-- 작성일: 2025-01-04
-- 설명: 모든 테이블과 컬럼에 대한 체계적인 코멘트 추가
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. TB_CONSULTATION (상담/예약 관리 테이블)
-- -----------------------------------------------------------------------------
-- 테이블 코멘트
ALTER TABLE TB_CONSULTATION COMMENT '상담 및 예약 관리 테이블';

-- 컬럼 코멘트
ALTER TABLE TB_CONSULTATION MODIFY COLUMN CNSLT_SEQ INT AUTO_INCREMENT COMMENT '상담/예약 일련번호';
ALTER TABLE TB_CONSULTATION MODIFY COLUMN NM VARCHAR(30) NOT NULL COMMENT '고객 이름';
ALTER TABLE TB_CONSULTATION MODIFY COLUMN TEL1 VARCHAR(20) NULL COMMENT '전화번호 (일반)';
ALTER TABLE TB_CONSULTATION MODIFY COLUMN TEL2 VARCHAR(20) NOT NULL COMMENT '휴대폰번호 (필수)';
ALTER TABLE TB_CONSULTATION MODIFY COLUMN ZIP VARCHAR(5) NULL COMMENT '우편번호';
ALTER TABLE TB_CONSULTATION MODIFY COLUMN ADRES1 VARCHAR(99) NULL COMMENT '기본주소';
ALTER TABLE TB_CONSULTATION MODIFY COLUMN ADRES2 VARCHAR(99) NULL COMMENT '상세주소';
ALTER TABLE TB_CONSULTATION MODIFY COLUMN SERVICE_CD VARCHAR(3) NULL COMMENT '서비스코드 (TB_CATEGORY 참조, 상담)';
ALTER TABLE TB_CONSULTATION MODIFY COLUMN PRODUCT_NO INT NULL COMMENT '상품번호 (TB_PRODUCT 참조, 예약)';
ALTER TABLE TB_CONSULTATION MODIFY COLUMN HOPE_DAY VARCHAR(8) NULL COMMENT '희망일자 (YYYYMMDD)';
ALTER TABLE TB_CONSULTATION MODIFY COLUMN INQRY_CN CLOB NOT NULL COMMENT '문의 내용';
ALTER TABLE TB_CONSULTATION MODIFY COLUMN REG_DT TIMESTAMP NOT NULL COMMENT '문의 등록일시';
ALTER TABLE TB_CONSULTATION MODIFY COLUMN PW VARCHAR(99) NULL COMMENT '비밀번호 (조회용)';
ALTER TABLE TB_CONSULTATION MODIFY COLUMN ANSWER CLOB NULL COMMENT '문의 답변 내용';
ALTER TABLE TB_CONSULTATION MODIFY COLUMN ANSWER_DT TIMESTAMP NULL COMMENT '답변 등록일시';
ALTER TABLE TB_CONSULTATION MODIFY COLUMN ANSWER_ID VARCHAR(30) NULL COMMENT '답변 작성자 ID';
ALTER TABLE TB_CONSULTATION MODIFY COLUMN STTUS_CD VARCHAR(3) NULL COMMENT '진행상태 코드';
ALTER TABLE TB_CONSULTATION MODIFY COLUMN REQ_TYPE VARCHAR(3) NOT NULL COMMENT '요청구분 (001:상담, 002:예약)';

-- -----------------------------------------------------------------------------
-- 2. TB_CASE (사례 관리 테이블)
-- -----------------------------------------------------------------------------
-- 테이블 코멘트
ALTER TABLE TB_CASE COMMENT '서비스 사례 관리 테이블';

-- 컬럼 코멘트
ALTER TABLE TB_CASE MODIFY COLUMN CASE_SEQ INT AUTO_INCREMENT COMMENT '사례 일련번호';
ALTER TABLE TB_CASE MODIFY COLUMN CASE_SJ VARCHAR(100) NOT NULL COMMENT '사례 제목';
ALTER TABLE TB_CASE MODIFY COLUMN CASE_CN CLOB NULL COMMENT '사례 내용';
ALTER TABLE TB_CASE MODIFY COLUMN REG_NM VARCHAR(50) NOT NULL COMMENT '작성자 ID';
ALTER TABLE TB_CASE MODIFY COLUMN FILE_SEQ INT NOT NULL COMMENT '대표이미지 파일번호 (TB_FILE 참조)';
ALTER TABLE TB_CASE MODIFY COLUMN HASHTAG VARCHAR(500) NULL COMMENT '해시태그 (쉼표 구분)';
ALTER TABLE TB_CASE MODIFY COLUMN RGS_DT TIMESTAMP NOT NULL COMMENT '등록일시';

-- -----------------------------------------------------------------------------
-- 3. TB_BOARD (게시판 관리 테이블)
-- -----------------------------------------------------------------------------
-- 테이블 코멘트
ALTER TABLE TB_BOARD COMMENT '게시판 관리 테이블';

-- 컬럼 코멘트
ALTER TABLE TB_BOARD MODIFY COLUMN BOARD_SEQ INT AUTO_INCREMENT COMMENT '게시글 일련번호';
ALTER TABLE TB_BOARD MODIFY COLUMN BOARD_GB VARCHAR(10) NOT NULL COMMENT '게시판 구분 (공지, FAQ, 포토 등)';
ALTER TABLE TB_BOARD MODIFY COLUMN NOTICE_YN CHAR(1) NOT NULL COMMENT '공지사항 여부 (Y/N)';
ALTER TABLE TB_BOARD MODIFY COLUMN BOARD_SJ VARCHAR(100) NOT NULL COMMENT '게시글 제목';
ALTER TABLE TB_BOARD MODIFY COLUMN BOARD_CN CLOB NULL COMMENT '게시글 내용';
ALTER TABLE TB_BOARD MODIFY COLUMN REG_NM VARCHAR(100) NOT NULL COMMENT '작성자명';
ALTER TABLE TB_BOARD MODIFY COLUMN RGS_DT TIMESTAMP NOT NULL COMMENT '등록일시';
ALTER TABLE TB_BOARD MODIFY COLUMN SECRET_YN CHAR(1) NULL COMMENT '비밀글 여부 (Y/N)';
ALTER TABLE TB_BOARD MODIFY COLUMN SECRET_PW VARCHAR(1000) NULL COMMENT '비밀글 비밀번호 (암호화)';

-- -----------------------------------------------------------------------------
-- 4. TB_FILE_RELATION (파일 관계 관리 테이블)
-- -----------------------------------------------------------------------------
-- 테이블 코멘트
ALTER TABLE TB_FILE_RELATION COMMENT '파일 연관관계 관리 테이블';

-- 컬럼 코멘트
ALTER TABLE TB_FILE_RELATION MODIFY COLUMN FILE_RELATE_SEQ INT AUTO_INCREMENT COMMENT '파일관계 일련번호';
ALTER TABLE TB_FILE_RELATION MODIFY COLUMN FILE_TRGET_SE VARCHAR(20) NOT NULL COMMENT '대상 구분 (CNSLT:상담, BOARD:게시판 등)';
ALTER TABLE TB_FILE_RELATION MODIFY COLUMN FILE_TRGET_SEQ INT NOT NULL COMMENT '대상 테이블 고유번호';
ALTER TABLE TB_FILE_RELATION MODIFY COLUMN FILE_SEQ INT NOT NULL COMMENT '파일 일련번호 (TB_FILE 참조)';
ALTER TABLE TB_FILE_RELATION MODIFY COLUMN RGS_DT TIMESTAMP NOT NULL COMMENT '등록일시';

-- -----------------------------------------------------------------------------
-- 5. TB_FILE (파일 정보 관리 테이블)
-- -----------------------------------------------------------------------------
-- 테이블 코멘트
ALTER TABLE TB_FILE COMMENT '파일 정보 관리 테이블';

-- 컬럼 코멘트
ALTER TABLE TB_FILE MODIFY COLUMN FILE_SEQ INT AUTO_INCREMENT COMMENT '파일 일련번호';
ALTER TABLE TB_FILE MODIFY COLUMN FILE_REAL_NM VARCHAR(500) NOT NULL COMMENT '원본 파일명';
ALTER TABLE TB_FILE MODIFY COLUMN FILE_FAKE_NM VARCHAR(500) NOT NULL COMMENT '저장 파일명 (시스템생성)';
ALTER TABLE TB_FILE MODIFY COLUMN FILE_PATH VARCHAR(100) NOT NULL COMMENT '파일 저장경로';
ALTER TABLE TB_FILE MODIFY COLUMN FILE_EXTSN VARCHAR(10) NOT NULL COMMENT '파일 확장자';
ALTER TABLE TB_FILE MODIFY COLUMN FILE_SIZE INT NOT NULL COMMENT '파일 크기 (bytes)';
ALTER TABLE TB_FILE MODIFY COLUMN RGS_DT TIMESTAMP NOT NULL COMMENT '등록일시';

-- -----------------------------------------------------------------------------
-- 6. TB_MANAGER (관리자 정보 테이블)
-- -----------------------------------------------------------------------------
-- 테이블 코멘트
ALTER TABLE TB_MANAGER COMMENT '시스템 관리자 정보 테이블';

-- 컬럼 코멘트
ALTER TABLE TB_MANAGER MODIFY COLUMN MNGR_SEQ INT AUTO_INCREMENT COMMENT '관리자 일련번호';
ALTER TABLE TB_MANAGER MODIFY COLUMN MNGR_ID VARCHAR(50) NOT NULL COMMENT '관리자 로그인 ID';
ALTER TABLE TB_MANAGER MODIFY COLUMN MNGR_PW VARCHAR(99) NOT NULL COMMENT '관리자 비밀번호 (암호화)';
ALTER TABLE TB_MANAGER MODIFY COLUMN MNGR_NM VARCHAR(20) NOT NULL COMMENT '관리자 성명';
ALTER TABLE TB_MANAGER MODIFY COLUMN MNGR_NCNM VARCHAR(20) NOT NULL COMMENT '관리자 닉네임/별칭';
ALTER TABLE TB_MANAGER MODIFY COLUMN MNGR_TEL VARCHAR(20) NULL COMMENT '관리자 연락처';
ALTER TABLE TB_MANAGER MODIFY COLUMN MNGR_STTUS CHAR(1) NOT NULL COMMENT '계정 상태 (A:활성, I:비활성, L:잠금)';
ALTER TABLE TB_MANAGER MODIFY COLUMN RGS_DT TIMESTAMP NOT NULL COMMENT '등록일시';

-- -----------------------------------------------------------------------------
-- 7. TB_CMMN_CODE (공통 코드 테이블)
-- -----------------------------------------------------------------------------
-- 테이블 코멘트
ALTER TABLE TB_CMMN_CODE COMMENT '시스템 공통코드 관리 테이블';

-- 컬럼 코멘트
ALTER TABLE TB_CMMN_CODE MODIFY COLUMN GROUP_CD CHAR(3) NOT NULL COMMENT '그룹코드 (대분류)';
ALTER TABLE TB_CMMN_CODE MODIFY COLUMN GROUP_NM VARCHAR(99) NOT NULL COMMENT '그룹코드명';
ALTER TABLE TB_CMMN_CODE MODIFY COLUMN CODE CHAR(3) NOT NULL COMMENT '상세코드 (소분류)';
ALTER TABLE TB_CMMN_CODE MODIFY COLUMN CODE_NM VARCHAR(99) NOT NULL COMMENT '상세코드명';
ALTER TABLE TB_CMMN_CODE MODIFY COLUMN CODE_USE_YN VARCHAR(1) NOT NULL COMMENT '코드 사용여부 (Y/N)';

-- -----------------------------------------------------------------------------
-- 8. TB_REVIEW (고객 후기 테이블)
-- -----------------------------------------------------------------------------
-- 테이블 코멘트
ALTER TABLE TB_REVIEW COMMENT '고객 서비스 후기 관리 테이블';

-- 컬럼 코멘트
ALTER TABLE TB_REVIEW MODIFY COLUMN REVIEW_SEQ INT AUTO_INCREMENT COMMENT '후기 일련번호';
ALTER TABLE TB_REVIEW MODIFY COLUMN REVIEW_NM VARCHAR(50) NOT NULL COMMENT '작성자명';
ALTER TABLE TB_REVIEW MODIFY COLUMN REVIEW_CN CLOB NOT NULL COMMENT '후기 내용';
ALTER TABLE TB_REVIEW MODIFY COLUMN STAR_RATE INT NOT NULL COMMENT '평점 (1~5점)';
ALTER TABLE TB_REVIEW MODIFY COLUMN SERVICE_CD VARCHAR(3) NULL COMMENT '서비스코드 (TB_CATEGORY 참조)';
ALTER TABLE TB_REVIEW MODIFY COLUMN PRODUCT_NO INT NULL COMMENT '상품번호 (TB_PRODUCT 참조)';
ALTER TABLE TB_REVIEW MODIFY COLUMN SVC_DATE VARCHAR(8) NULL COMMENT '서비스 이용일자 (YYYYMMDD)';
ALTER TABLE TB_REVIEW MODIFY COLUMN DISP_YN CHAR(1) NOT NULL COMMENT '노출여부 (Y/N)';
ALTER TABLE TB_REVIEW MODIFY COLUMN PW VARCHAR(99) NULL COMMENT '비밀번호 (수정/삭제용)';
ALTER TABLE TB_REVIEW MODIFY COLUMN RGS_DT TIMESTAMP NOT NULL COMMENT '등록일시';

-- -----------------------------------------------------------------------------
-- 9. TB_CATEGORY (서비스 카테고리 테이블) - 기존 코멘트 보완
-- -----------------------------------------------------------------------------
-- 테이블 코멘트 (이미 존재하나 명확히 재정의)
ALTER TABLE TB_CATEGORY COMMENT '서비스 카테고리 정보 관리 테이블';

-- 컬럼 코멘트 (기존 코멘트 보완)
ALTER TABLE TB_CATEGORY MODIFY COLUMN SERVICE_CD VARCHAR(3) NOT NULL COMMENT '서비스코드 (Primary Key)';
ALTER TABLE TB_CATEGORY MODIFY COLUMN SERVICE_NM VARCHAR(100) NOT NULL COMMENT '서비스명';
ALTER TABLE TB_CATEGORY MODIFY COLUMN SERVICE_ORDER INT DEFAULT 0 COMMENT '노출 정렬순서';
ALTER TABLE TB_CATEGORY MODIFY COLUMN USE_YN VARCHAR(1) DEFAULT 'Y' COMMENT '사용여부 (Y/N)';
ALTER TABLE TB_CATEGORY MODIFY COLUMN DEL_YN VARCHAR(1) DEFAULT 'N' COMMENT '삭제여부 (Y/N, 논리삭제)';
ALTER TABLE TB_CATEGORY MODIFY COLUMN REG_USER_ID VARCHAR(50) COMMENT '등록자 ID';
ALTER TABLE TB_CATEGORY MODIFY COLUMN REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시';
ALTER TABLE TB_CATEGORY MODIFY COLUMN MOD_USER_ID VARCHAR(50) COMMENT '수정자 ID';
ALTER TABLE TB_CATEGORY MODIFY COLUMN MOD_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '최종수정일시';

-- -----------------------------------------------------------------------------
-- 10. TB_PRODUCT (상품 정보 테이블) - 기존 코멘트 유지/보완
-- -----------------------------------------------------------------------------
-- 테이블 코멘트는 이미 존재함
-- 컬럼 코멘트는 이미 존재하나 필요시 재정의 가능
-- 아래는 참고용으로 주석 처리
/*
ALTER TABLE TB_PRODUCT COMMENT '상품 정보 관리 테이블';
ALTER TABLE TB_PRODUCT MODIFY COLUMN PRODUCT_NO INT AUTO_INCREMENT COMMENT '상품번호';
ALTER TABLE TB_PRODUCT MODIFY COLUMN SERVICE_CD VARCHAR(3) NOT NULL COMMENT '서비스코드 (TB_CATEGORY 참조)';
ALTER TABLE TB_PRODUCT MODIFY COLUMN PRODUCT_NM VARCHAR(200) NOT NULL COMMENT '상품명';
ALTER TABLE TB_PRODUCT MODIFY COLUMN PRODUCT_DESC CLOB COMMENT '상품 상세설명';
ALTER TABLE TB_PRODUCT MODIFY COLUMN AREA_TYPE VARCHAR(50) COMMENT '적용평형 (예: 20-30평형)';
ALTER TABLE TB_PRODUCT MODIFY COLUMN ORIGINAL_PRICE INT DEFAULT 0 COMMENT '정가';
ALTER TABLE TB_PRODUCT MODIFY COLUMN SALE_PRICE INT DEFAULT 0 COMMENT '판매가';
ALTER TABLE TB_PRODUCT MODIFY COLUMN DISCOUNT_RATE INT DEFAULT 0 COMMENT '할인율 (%)';
ALTER TABLE TB_PRODUCT MODIFY COLUMN SERVICE_TIME VARCHAR(50) COMMENT '서비스 소요시간';
ALTER TABLE TB_PRODUCT MODIFY COLUMN SERVICE_INCLUDES CLOB COMMENT '서비스 포함사항 (JSON)';
ALTER TABLE TB_PRODUCT MODIFY COLUMN DISPLAY_ORDER INT DEFAULT 999 COMMENT '노출순서';
ALTER TABLE TB_PRODUCT MODIFY COLUMN DISPLAY_YN VARCHAR(1) DEFAULT 'Y' COMMENT '노출여부 (Y/N)';
ALTER TABLE TB_PRODUCT MODIFY COLUMN SALE_YN VARCHAR(1) DEFAULT 'Y' COMMENT '판매여부 (Y/N)';
ALTER TABLE TB_PRODUCT MODIFY COLUMN DEL_YN VARCHAR(1) DEFAULT 'N' COMMENT '삭제여부 (Y/N, 논리삭제)';
ALTER TABLE TB_PRODUCT MODIFY COLUMN REG_USER_ID VARCHAR(50) COMMENT '등록자 ID';
ALTER TABLE TB_PRODUCT MODIFY COLUMN REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시';
ALTER TABLE TB_PRODUCT MODIFY COLUMN MOD_USER_ID VARCHAR(50) COMMENT '수정자 ID';
ALTER TABLE TB_PRODUCT MODIFY COLUMN MOD_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '최종수정일시';
*/

-- =============================================================================
-- 실행 완료 메시지
-- =============================================================================
-- 모든 테이블과 컬럼에 대한 코멘트가 추가되었습니다.
-- 데이터베이스 메타데이터를 통해 코멘트를 확인할 수 있습니다.

-- 코멘트 확인 쿼리 예시:
/*
-- 테이블 코멘트 조회
SELECT 
    TABLE_NAME,
    TABLE_COMMENT 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = DATABASE()
ORDER BY TABLE_NAME;

-- 컬럼 코멘트 조회
SELECT 
    TABLE_NAME,
    COLUMN_NAME,
    COLUMN_COMMENT,
    COLUMN_TYPE,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME IN (
        'TB_CONSULTATION', 'TB_CASE', 'TB_BOARD', 
        'TB_FILE_RELATION', 'TB_FILE', 'TB_MANAGER',
        'TB_CMMN_CODE', 'TB_REVIEW', 'TB_CATEGORY', 'TB_PRODUCT'
    )
ORDER BY TABLE_NAME, ORDINAL_POSITION;
*/