-- V002: TB_CASE 테이블에 FILE_SEQ2 컬럼 추가
-- 실행: mysql -h localhost -u ksm1779 -p ksm1779 < V002_add_file_seq2.sql

ALTER TABLE TB_CASE ADD COLUMN FILE_SEQ2 INT(11) DEFAULT NULL COMMENT '대표이미지2 파일번호' AFTER FILE_SEQ;
ALTER TABLE TB_CASE ADD KEY IDX_CASE_FILE2 (FILE_SEQ2);
