-- ============================================================================
-- 상품 대표이미지 6개 확장 마이그레이션
-- ============================================================================

-- 기존 THUMBNAIL_SEQ를 FILE_SEQ1로 변경하고 FILE_SEQ2~6 추가
ALTER TABLE TB_PRODUCT
    CHANGE COLUMN THUMBNAIL_SEQ FILE_SEQ1 INT(11) DEFAULT NULL COMMENT '대표이미지1 파일번호',
    ADD COLUMN FILE_SEQ2 INT(11) DEFAULT NULL COMMENT '대표이미지2 파일번호' AFTER FILE_SEQ1,
    ADD COLUMN FILE_SEQ3 INT(11) DEFAULT NULL COMMENT '대표이미지3 파일번호' AFTER FILE_SEQ2,
    ADD COLUMN FILE_SEQ4 INT(11) DEFAULT NULL COMMENT '대표이미지4 파일번호' AFTER FILE_SEQ3,
    ADD COLUMN FILE_SEQ5 INT(11) DEFAULT NULL COMMENT '대표이미지5 파일번호' AFTER FILE_SEQ4,
    ADD COLUMN FILE_SEQ6 INT(11) DEFAULT NULL COMMENT '대표이미지6 파일번호' AFTER FILE_SEQ5;

-- 인덱스 추가
ALTER TABLE TB_PRODUCT
    ADD INDEX IDX_PRODUCT_FILE1 (FILE_SEQ1),
    ADD INDEX IDX_PRODUCT_FILE2 (FILE_SEQ2),
    ADD INDEX IDX_PRODUCT_FILE3 (FILE_SEQ3),
    ADD INDEX IDX_PRODUCT_FILE4 (FILE_SEQ4),
    ADD INDEX IDX_PRODUCT_FILE5 (FILE_SEQ5),
    ADD INDEX IDX_PRODUCT_FILE6 (FILE_SEQ6);
