-- V005: TB_CONSULTATION 테이블에 이메일, 업체명, 희망시간 컬럼 추가
-- 서비스 신청 폼의 추가 필드 지원

-- 이메일 컬럼 추가
ALTER TABLE `TB_CONSULTATION`
ADD COLUMN `EMAIL` VARCHAR(100) DEFAULT NULL COMMENT '이메일 주소'
AFTER `TEL2`;

-- 업체명 컬럼 추가
ALTER TABLE `TB_CONSULTATION`
ADD COLUMN `COMP_NM` VARCHAR(100) DEFAULT NULL COMMENT '업체명/회사명'
AFTER `EMAIL`;

-- 희망시간 컬럼 추가
ALTER TABLE `TB_CONSULTATION`
ADD COLUMN `HOPE_TIME` VARCHAR(20) DEFAULT NULL COMMENT '희망시간 (예: 09:00 - 10:00)'
AFTER `HOPE_DAY`;

-- 인덱스 추가 (이메일 검색용)
CREATE INDEX `IDX_CONSULTATION_EMAIL` ON `TB_CONSULTATION` (`EMAIL`);
