-- 고객센터 설명 필드 추가 (CONTACT 그룹)
INSERT INTO TB_CONFIG (CONFIG_KEY, CONFIG_VALUE, CONFIG_DESC, CONFIG_GROUP, CONFIG_TYPE, DISPLAY_ORDER) VALUES
('PHONE_DESCRIPTION', '09:00 - 18:00(8시간 상담 가능)', '전화번호 설명', 'CONTACT', 'TEXT', 14),
('EMAIL_DESCRIPTION', '이메일 문의', '이메일 설명', 'CONTACT', 'TEXT', 15),
('BRANCH_NAME', '서울지사', '지점명', 'CONTACT', 'TEXT', 16)
ON DUPLICATE KEY UPDATE CONFIG_KEY=CONFIG_KEY;

-- 고객센터 정보 업데이트 (사용자 요청 데이터)
UPDATE TB_CONFIG SET CONFIG_VALUE = '02-3662-0332' WHERE CONFIG_KEY = 'PHONE';
UPDATE TB_CONFIG SET CONFIG_VALUE = 'careville0424@naver.com' WHERE CONFIG_KEY = 'EMAIL';
UPDATE TB_CONFIG SET CONFIG_VALUE = '평일 09:00 - 18:00' WHERE CONFIG_KEY = 'HOURS_WEEKDAY';
UPDATE TB_CONFIG SET CONFIG_VALUE = '주말 휴무' WHERE CONFIG_KEY = 'HOURS_WEEKEND';
UPDATE TB_CONFIG SET CONFIG_VALUE = '09:00 - 18:00(8시간 상담 가능)' WHERE CONFIG_KEY = 'PHONE_DESCRIPTION';
